name: AutoFetchCFIP

on:
  schedule:
    - cron: "0 */6 * * *"   # 每6小时运行一次
  workflow_dispatch:         # 手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 🔑 允许 workflow 推送代码
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python cf_auto.py

      - name: Commit results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ip.txt
          git commit -m "update ip.txt" || echo "No changes"
          git push
